include::../resources/header.adoc[]
include::../resources/styles.adoc[]
ifndef::root[:root: ../../]
ifndef::menu[:menu: menu.adoc]

:on-screen-menu: xref:{menu}#menu[on-screen menu]
:vice: xref:https://vice-emu.sourceforge.io/vice_1.html#SEC11[Vice]

== Controller Mapping (xInput)

The following key mappings directly apply to "xInput" devices, such as the Xbox-One controller. Different controllers such as the Switch controller and the Playstation 4/5 controller have nearly identical mapping, where buttons in similar positions perform the same function as their xInput counterparts

[%header, cols="^.^, ^.^, ^.^"]
[width=80%]
[.center]
|===
| Joystick | Controller  | Controller Alt.
| UP       | D-Pad UP    | Button B
| DOWN     | D-Pad DOWN  | Button X
| LEFT     | D-Pad LEFT  | Left Analog
| RIGHT    | D-Pad RIGHT | Left Analog
| FIRE     | Button A    | Button Y (Autofire)
|===

[[button-map]]
Controller buttons not mentioned in the table above can be mapped to trigger any keyboard keystroke through the {on-screen-menu}. Default Controller-Keyboard mappings are reported below:

[%header, cols="^.^, ^.^"]
[width=80%]
[.center]
|===
| Keyboard | Controller
| SPACE    | Menu Button
| F1       | Right Shoulder
|===

[[autofire]]
=== Autofire
The "Y Button" is dedicated to autofire, which can be configured from inactive to 10Hz (100ms) fire-rate through the {on-screen-menu}

[[swap-ports]]
=== Swapping Joystick Ports
Joystick ports assigned to the connected bluetooth controllers can be swapped with the "View + Y" key combination on the controller.
If two controllers are currently connected, only the controller currently assigned to joystick port 2 can swap the ports (to prevent pesky little siblings or partners from swapping ports in-game)


[[keyboard-map]]
== Keyboard Mapping
At the moment Blue-64 **only supports the English US layout**. The key mapping can be switched between "symbolic" and "positional ({vice})" through the {on-screen-menu}. With "symbolic" mapping the keys on the bluetooth keyboard do exactly what they say on the label, including their "shift" function (if applicable) with a few exceptions:

[%header, cols="^.^, ^.^"]
[width=80%]
[.center]
|===
| En-US Key (symbolic) | C64 Key
| '~'             | Arrow Left
| '\'             | Arrow Up
| 6+Shift         | £
| Tab / Shift+Tab | Stop / Run
| Esc             | Restore
| Delete, F12     | Clear
| Home, F9        | Home
| Insert, F10     | Insert
| Start (Windows) | Commodore
| Shift+'\'       | Pi
|===
