include::../resources/header.adoc[]
ifndef::root[:root: ../../]
ifndef::mapping[:mapping: mapping.adoc]

:keyboard-mapping-profile: xref:{mapping}#keyboard-map[keyboard mapping profile]
:mapping-unused-controller-buttons: xref:{mapping}#butto-map[Mapping unused controller buttons]
:autofire: xref:{mapping}#autofire[Autofire]

[[menu]]
== On-Screen Menu & Additional Functions
Blue-64 has an internal menu that is visualized by printing text on screen. The menu allows typing and executing frequently used macros like loading the tape, loading and/or running programs from disk drive etc. as well as configuring additional preferences such as:

- Selecting {keyboard-mapping-profile}
- {mapping-unused-controller-buttons}
- Enabling/configuring {autofire}

[%header, cols="^.^, ^.^"]
[width=80%]
[.center]
|===
| Function                     | Button(s)
| Swap Player 1-2              | View + Y
| Cycle Menu (controller)      | View + A/B
| Select/Run Menu (controller) | View + Menu
| Exit Menu (controller)       | View + X
| Cycle Menu (keyboard)        | Alt/AltGr + Up/Down/Left/Right Arrow
| Select/Run Menu (keyboard)   | Alt/AltGr + Enter
| Exit Menu (keyboard)         | Alt/AltGr + Backspace
|===

NOTE: Please beware that the "view" and "menu" buttons may be called differently on non xInput devices but are generally in similar positions

NOTE: Please beware that some controllers, such as 8bitDo or Switch controllers have X-Y and A-B button labels swapped compared to a regular Xbox controllers. What matters in this case is the buttons' position, not the label, so for instance the A button will always be the one of the bottom regardless of the label
